pub mod deleter;
pub mod device;
pub mod downloader;
pub mod model_type_vosk;
pub mod model_type_whisper;
mod recognizer;
pub mod record;
mod sqlite;
mod transcriber;
pub mod transcription;
pub mod transcription_online;
pub mod chat_online;
mod writer;
