pub mod deleter;
pub mod device;
pub mod downloader;
pub mod model_type_vosk;
pub mod model_type_whisper;
pub mod model_type_nllb;
mod recognizer;
pub mod record;
mod sqlite;
mod transcriber;
pub mod transcription;
pub mod transcription_online;
mod translator;
mod writer;
mod speaker;