pub mod chat_online;
pub mod deleter;
pub mod device;
pub mod downloader;
pub mod model_type_vosk;
pub mod model_type_whisper;
pub mod permissions;
mod recognizer;
pub mod record;
pub mod record_desktop;
mod sqlite;
mod transcriber;
pub mod transcription;
pub mod transcription_amivoice;
pub mod transcription_online;
pub mod translation_ja;
mod writer;
pub mod screenshot;